from django.urls import path
from . import views

urlpatterns = [
    path('', views.home, name='home'),
    path('register/', views.register, name='register'),
    path('login/', views.login_view, name='login'),
    path('logout/', views.logout_view, name='logout'),
    path('profile/', views.profile, name='profile'),
    path('apply-seller/', views.apply_seller, name='apply_seller'),
    path('seller-requests/', views.seller_requests, name='seller_requests'),
    path('seller-requests/<int:pk>/approve/', views.approve_seller, name='approve_seller'),
    path('seller-requests/<int:pk>/reject/', views.reject_seller, name='reject_seller'),
    path('sell-zone/', views.sell_zone, name='sell_zone'),
    path('sell-zone/add-product/', views.add_product, name='add_product'),
    path('sell-zone/delete-product/<int:product_id>/', views.delete_product, name='delete_product'),
    path('sell-zone/orders/', views.seller_orders, name='seller_orders'),
    path('sell-zone/cancel-order/<int:order_id>/', views.cancel_order, name='cancel_order'),
    path('sell-zone/update-order-status/<int:order_id>/', views.update_order_status, name='update_order_status'),
    path('product/<int:pk>/', views.product_detail, name='product_detail'),
    path('cart/add/<int:product_id>/', views.add_to_cart, name='add_to_cart'),
    path('cart/', views.cart_view, name='cart'),
    path('cart/update/<int:item_id>/', views.update_cart, name='update_cart'),
    path('cart/remove/<int:item_id>/', views.remove_cart_item, name='remove_cart_item'),
    path('place-order/', views.place_order, name='place_order'),
    path('orders/', views.order_tracking, name='order_tracking'),
    path('product/<int:pk>/review/', views.submit_review, name='submit_review'),
    path('product/<int:pk>/chat/', views.product_chat, name='product_chat'),
    path('search/', views.search_products, name='search_products'),
    path('product/update/<int:pk>/', views.update_product, name='update_product'),
    path('category/add/', views.add_category, name='add_category'),
    path('categories/', views.categories, name='categories'),
    path('category/<int:category_id>/', views.category_products, name='category_products'),
    path('about/', views.about, name='about'),
    path('policies/', views.all_policies, name='all_policies'),
    path('terms-conditions/', views.terms_conditions, name='terms_conditions'),
    path('orders/cancel/<int:order_id>/', views.cancel_user_order, name='cancel_user_order'),
    path('sell-zone/messages/', views.seller_messages, name='seller_messages'),
    path('orders/messages/', views.buyer_messages_in_orders, name='buyer_messages_in_orders'),
    path('sell-zone/messages/reply/<int:product_id>/', views.reply_to_message, name='reply_to_message'),
    path('orders/messages/reply/buyer/<int:product_id>/', views.buyer_reply_to_message, name='buyer_reply_to_message'),
    path('apply-seller-status/', views.apply_seller_status, name='apply_seller_status'),

]
